<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class MasterDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();
        $positions = [
            ['name' => 'Administrator', 'created_at' => $now],
            ['name' => 'Guru Kelas / Pengajar', 'created_at' => $now],
            ['name' => 'Wali Kelas', 'created_at' => $now],
            ['name' => 'Guru Piket', 'created_at' => $now],
            ['name' => 'Penanggung Jawab Kegiatan', 'created_at' => $now],
            ['name' => 'PH (Penanggung Jawab Harian)', 'created_at' => $now],
            ['name' => 'Kepala Departemen', 'created_at' => $now],
            ['name' => 'Kepala Sekolah', 'created_at' => $now],
        ];

        DB::table('positions')->insert($positions);

        // Default Users with Single or Multiple Positions
        $defaultUsers = [
            ['name' => 'Aga Yanu', 'username' => 'agayanu', 'password' => Hash::make('admin123'), 'gender' => 'L', 'position' => 1, 'user' => 'system', 'positions' => [1], 'created_at' => $now],
            ['name' => 'Dr. Iwan Cakrayana, S.T., S.Pd., M.Si., Gr.', 'username' => 'icakrayana', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 8, 'user' => 'system', 'positions' => [8], 'created_at' => $now],
            ['name' => 'Afra Fitriani, S.S., S.Pd., M.Pd., Gr.', 'username' => 'afitriani', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 8, 'user' => 'system', 'positions' => [8], 'created_at' => $now],
            ['name' => 'Nasukha Z.,M.Pd.', 'username' => 'nasukha', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 7, 'user' => 'system', 'positions' => [2,7], 'created_at' => $now],
            ['name' => 'Iwan Gunawan M.Pd', 'username' => 'iwangunawan', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 7, 'user' => 'system', 'positions' => [2,7], 'created_at' => $now],
            ['name' => 'Freddy Siahaan M.Pd', 'username' => 'freddysiahaan', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 7, 'user' => 'system', 'positions' => [2,7], 'created_at' => $now],
            ['name' => 'Ari Sucipto, SS.BA, MTSOOL', 'username' => 'arisucipto', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 7, 'user' => 'system', 'positions' => [2,3,7], 'created_at' => $now],
            ['name' => 'Liddia Hendriati , M.Pd', 'username' => 'liddiahendriati', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 6, 'user' => 'system', 'positions' => [2,3,6], 'created_at' => $now],
            ['name' => 'Ika Septianawati M.Pd', 'username' => 'ikaseptianawati', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 6, 'user' => 'system', 'positions' => [2,3,6], 'created_at' => $now],
            ['name' => 'Sri Hayati,M.Pd.', 'username' => 'srihayati', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 6, 'user' => 'system', 'positions' => [2,3,6], 'created_at' => $now],
            ['name' => 'Oskal Frananda, S.Kom', 'username' => 'oskalfrananda', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 6, 'user' => 'system', 'positions' => [2,6], 'created_at' => $now],
            ['name' => 'Yanuar Hardi H.,S.Pd.Si.Gr', 'username' => 'yanuarhardi', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 6, 'user' => 'system', 'positions' => [2,6], 'created_at' => $now],
            ['name' => 'Titi Rahmawati, S.Si.MT.Gr', 'username' => 'titirahmawati', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 6, 'user' => 'system', 'positions' => [2,3,6], 'created_at' => $now],
            ['name' => 'Supriyadi, S.Kom', 'username' => 'supriyadi', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 6, 'user' => 'system', 'positions' => [2,3,6], 'created_at' => $now],
            ['name' => 'Aman Abdurahman,S.Pdi.', 'username' => 'amanabdurahman', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 6, 'user' => 'system', 'positions' => [2,6], 'created_at' => $now],
            ['name' => 'Purwonugroho, S.Pd.Gr.', 'username' => 'purwonugroho', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 6, 'user' => 'system', 'positions' => [2,3,6], 'created_at' => $now],
            ['name' => 'Wirya Aini,M.Pd.', 'username' => 'wiryaaini', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'R Sri Wilujeng S.Pd, M.Pd', 'username' => 'rsriwilujeng', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Dra. Ai Nurfaridah', 'username' => 'ainurfaridah', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Dra. Hj. Rini Komalasari', 'username' => 'rinikomalasari', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Asih Mulyani, S.Kom', 'username' => 'asihmulyani', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Syarifah, M.Pdi.', 'username' => 'syarifah', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3,5], 'created_at' => $now],
            ['name' => 'Ike Yuniawati, S.Pd', 'username' => 'ikeyuniawati', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Tri Rahayu, M.Pd.', 'username' => 'trirahayu', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Fery Yantini, M.Pd', 'username' => 'feryyantini', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Ahmad Muhammad, S.Kom.', 'username' => 'ahmadmuhammad', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,5], 'created_at' => $now],
            ['name' => 'Gina Fariani, S.P.', 'username' => 'ginafariani', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Juju Juriah, S.P', 'username' => 'jujujuriah', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Iwan Sutiawan, S.Pd.', 'username' => 'iwansutiawan', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Fia Fianti, M.Pd.', 'username' => 'fiafianti', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Dedi Masri, S.Pd', 'username' => 'dedimasri', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Giyanti S.Pd', 'username' => 'giyanti', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Dhiena Farida, S.T', 'username' => 'dhienafarida', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3,4,5], 'created_at' => $now],
            ['name' => 'Eki Syukeri,S.Pd.', 'username' => 'ekisyukeri', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Siti Ubahiyah,SE. M.Pd.', 'username' => 'sitiubahiyah', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3,5], 'created_at' => $now],
            ['name' => 'Ika Muharyani,S.Pd.Gr.', 'username' => 'ikamuharyani', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Nisa Merdekawati,S.Psi. Gr', 'username' => 'nisamerdekawati', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,4,5], 'created_at' => $now],
            ['name' => 'Tiodora Sabarina,M.Pd.Gr', 'username' => 'tiodorasabarina', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Dwi Apriyani, S.Pd.Gr.', 'username' => 'dwiapriyani', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Dwi  Oktaviani,S.Psi. Gr', 'username' => 'dwioktaviani', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,4,5], 'created_at' => $now],
            ['name' => 'Diana Mustika Sari,S.Pd. Gr', 'username' => 'dianamustikasari', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Ai Warni, S.Pd.', 'username' => 'aiwarni', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Dinda Oktavia,A.Md.', 'username' => 'dindaoktavia', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,4], 'created_at' => $now],
            ['name' => 'Giri Indah Sari,S.Pd. Gr', 'username' => 'giriindahsari', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Wenza Anugrah,S.Pd.', 'username' => 'wenzaanugrah', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,4], 'created_at' => $now],
            ['name' => 'Januar Ambarwati,S.Pd.Gr.', 'username' => 'januarambarwati', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => "Ahmad Rifa'i,S.Pdi.", 'username' => 'ahmadrifai', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Geane Siskarani Yuanova,S.Psi.', 'username' => 'geanesiskaraniyuanova', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,4,5], 'created_at' => $now],
            ['name' => 'Dwi Pratiwi,S.Pd. Gr', 'username' => 'dwipratiwi', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Yusi Rakhmah Wati,S.Pd. Gr', 'username' => 'yusirakhmahwati', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Mukti Alinur,M.Pd.Gr', 'username' => 'muktialinur', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Intan Baedari, S.Pd.Gr', 'username' => 'intanbaedari', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Rizki Nurul Hidayah,S.Pd.Gr', 'username' => 'rizkinurulhidayah', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Annisa Febriana, P.Psi.', 'username' => 'annisafebriana', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,5], 'created_at' => $now],
            ['name' => 'Rizky Julian Pangestu Aji, S.Pd. Gr', 'username' => 'rizkyjulianpangestuaji', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,3,5], 'created_at' => $now],
            ['name' => 'Rendy Refsan Yami,S.Pd.', 'username' => 'rendyrefsanyami', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,4,5], 'created_at' => $now],
            ['name' => 'Kemala Saras Rianti, S.Pd.Gr', 'username' => 'kemalasarasrianti', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Nurzaman,S.Pd.Gr', 'username' => 'nurzaman', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,3,5], 'created_at' => $now],
            ['name' => 'Fikri Maulana Ridho, S.Pd', 'username' => 'fikrimaulanaridho', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Aditya Dwi Nugroho, S.Pd.Gr', 'username' => 'adityadwinugroho', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Asyifa Qolby Rakhaputri, S.Kom', 'username' => 'asyifaqolbyrakhaputri', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Lutfi Febrianyah, S.Pd', 'username' => 'lutfifebrianyah', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,4], 'created_at' => $now],
            ['name' => 'Annisa Marheliyana, S.Pd.', 'username' => 'annisamarheliyana', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Muhammad Falahaen Jiddan,S.Pd.', 'username' => 'muhammadfalahaenjiddan', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Rahmat Robani, S.Or.', 'username' => 'rahmatrobani', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,4], 'created_at' => $now],
            ['name' => 'Dwi Murni Melisa Putri, S.Pd.Gr', 'username' => 'dwimurnimelisaputri', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3,5], 'created_at' => $now],
            ['name' => 'Nurul Indah Fitriana, S.Pd. Gr', 'username' => 'nurulindahfitriana', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Maya Nurul, S.Pd.Gr', 'username' => 'mayanurul', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3,5], 'created_at' => $now],
            ['name' => 'Chamelia Asmarafuti, M.Pd', 'username' => 'chameliaasmarafuti', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Indira Giri Dwi Prameswari, S.Pd', 'username' => 'indiragiridwiprameswari', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Meli Nuryanti Amir, S.Psi.', 'username' => 'melinuryantiamir', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,5], 'created_at' => $now],
            ['name' => 'Chafidha Torenia W, S.Pd', 'username' => 'chafidhatoreniaw', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Rizal F, S.Pd', 'username' => 'rizalf', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Yeti Susilawati, S.Pd', 'username' => 'yetisusilawati', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3,5], 'created_at' => $now],
            ['name' => 'Puti Ayudya, S.Sos', 'username' => 'putiayudya', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Muhammad Ardi Budiawan, S.Pd', 'username' => 'muhammadardibudiawan', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,3,5], 'created_at' => $now],
            ['name' => 'Farras Alifa Semendawai, S.Sos. M.Han', 'username' => 'farrasalifasemendawai', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Rizky Lingga Ayuningtyas, M.H', 'username' => 'rizkylinggaayuningtyas', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,4], 'created_at' => $now],
            ['name' => 'Uyan Ahmad Satibi, M.Pd', 'username' => 'uyanahmadsatibi', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,3,5], 'created_at' => $now],
            ['name' => 'Nurul Asih, S.Pd', 'username' => 'nurulasih', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3,5], 'created_at' => $now],
            ['name' => 'Indah Larasati, S.Sos', 'username' => 'indahlarasati', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Khanza Bilbina, S.Pd', 'username' => 'khanzabilbina', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3,5], 'created_at' => $now],
            ['name' => 'Luthfia Rahma, ', 'username' => 'luthfiarahma', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Novika Priliyana, S.Pd.Gr', 'username' => 'novikapriliyana', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Tio Dwi Akbar, S.T', 'username' => 'tiodwiakbar', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Shafa Dania, S.Kom', 'username' => 'shafadania', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3], 'created_at' => $now],
            ['name' => 'Anugrah, S.Pd', 'username' => 'anugrah', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,4], 'created_at' => $now],
            ['name' => 'Raisya Nasywa A, S.Pd', 'username' => 'raisyanasywaa', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3,5], 'created_at' => $now],
            ['name' => 'Muhammad Nabil Fauzul, S.Pd', 'username' => 'muhammadnabilfauzul', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2,3,5], 'created_at' => $now],
            ['name' => 'Gita Ayundari, S.Pd.Gr', 'username' => 'gitaayundari', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3,4], 'created_at' => $now],
            ['name' => 'Farely, S.Pd', 'username' => 'farely', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,3,4], 'created_at' => $now],
            ['name' => 'Ria Sulistiawati, S.Pd.Gr', 'username' => 'riasulistiawati', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2,4], 'created_at' => $now],
            ['name' => 'Ilham Aulia', 'username' => 'ilhamaulia', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 4, 'user' => 'system', 'positions' => [4], 'created_at' => $now],
            ['name' => 'Nur Adita', 'username' => 'nuradita', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Astari Sekar S., S.Hum.', 'username' => 'astarisekars', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Nurulia Falah, S.Sos.', 'username' => 'nuruliafalah', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Roni Hermawan', 'username' => 'ronihermawan', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Herlambang Irdiansyah S.', 'username' => 'herlambangirdiansyahs', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Rohajon', 'username' => 'rohajon', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Andi Sylvia F., S.E., A.Md.Kep', 'username' => 'andisylviaf', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Dian Adesti, S.Kom.', 'username' => 'dianadesti', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Nuri Nurjannah H., S.Pd.', 'username' => 'nurinurjannahh', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Dewi Maytasari Diyani, S.Pd.', 'username' => 'dewimaytasaridiyani', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Kukuh Firdaus', 'username' => 'kukuhfirdaus', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Hodirin Susanto', 'username' => 'hodirinsusanto', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Ilham Eka Permana', 'username' => 'ilhamekapermana', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Eneng Hindayah, S.Sn.', 'username' => 'enenghindayah', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Dra. Rini Diah Astuti', 'username' => 'rinidiahastuti', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Novani Nur Wijaya', 'username' => 'novaninurwijaya', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Dewinta Nurhayati, S.Pd.', 'username' => 'dewintanurhayati', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Dra. Kania Dewi', 'username' => 'kaniadewi', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Muhidin, S.Kom', 'username' => 'muhidin', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Aga Yanupraba, S.T.', 'username' => 'agayanupraba', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 2, 'user' => 'system', 'positions' => [2], 'created_at' => $now],
            ['name' => 'Auliya Dhava Wima', 'username' => 'auliyadhavawima', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'Muhammad Farhan Aula, S.Kom.', 'username' => 'muhammadfarhanaula', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'Yanda Muhaimin', 'username' => 'kegiatan', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'Rodalih, S.Pd.I.', 'username' => 'rodalih', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'dr. Dewi Maulida Apsari', 'username' => 'dewimaulidaapsari', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'Vija Saputra, S.E.', 'username' => 'vijasaputra', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'Dini Aliyanih, S.Pd.', 'username' => 'dinialiyanih', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'Abdul Hakim', 'username' => 'abdulhakim', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'Nailla Azzahra Nur Ashyfa, S.Pd', 'username' => 'naillaazzahranurashyfa', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'Fatahillah', 'username' => 'fatahillah', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'Achmad Rizky Eka Syaputra', 'username' => 'achmadrizkyekasyaputra', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'Rizal Afrianto Wibowo, S.T. ', 'username' => 'rizalafriantowibowo', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'Guntur Cahyono', 'username' => 'gunturcahyono', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'Rendra Irawan A.Md S.Pd', 'username' => 'rendrairawana.mds.pd', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'SAPUTRI QURNIASARI', 'username' => 'saputriqurniasari', 'password' => Hash::make('123456'), 'gender' => 'P', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'Wahyudi', 'username' => 'wahyudi', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'Doni Dartafian Amirudin  S.Pd., Gr. ', 'username' => 'donidartafianamirudins.pd.', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now],
            ['name' => 'Ujang Ruspendi', 'username' => 'ujangruspendi', 'password' => Hash::make('123456'), 'gender' => 'L', 'position' => 5, 'user' => 'system', 'positions' => [5], 'created_at' => $now]
        ];

        DB::table('users')->insert($defaultUsers);
    }
}
